-- Typed models for the SeqbenchMcp SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class AlphafoldLookup
---@field accession string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class AlphafoldLookupCreateData
---@field accession string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class AsoDesign
---@field gate? any
---@field length? number
---@field ok any
---@field provenance table
---@field result table
---@field target string
---@field tool string
---@field wing? number

---@class AsoDesignCreateData
---@field gate? any
---@field length? number
---@field ok any
---@field provenance table
---@field result table
---@field target string
---@field tool string
---@field wing? number

---@class BaseEditingDesign
---@field editor? string
---@field frame_start? number
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field target string
---@field target_position? number
---@field tool string

---@class BaseEditingDesignCreateData
---@field editor? string
---@field frame_start? number
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field target string
---@field target_position? number
---@field tool string

---@class Batch
---@field arg? table
---@field input string
---@field ok any
---@field result table
---@field tool string

---@class BatchLoadMatch
---@field arg? table
---@field input? string
---@field ok? any
---@field result? table
---@field tool? string

---@class BatchCreateData
---@field arg? table
---@field input string
---@field ok any
---@field result table
---@field tool string

---@class BatchWorkflow
---@field input string
---@field ok any
---@field result table
---@field step table

---@class BatchWorkflowLoadMatch
---@field input? string
---@field ok? any
---@field result? table
---@field step? table

---@class BatchWorkflowCreateData
---@field input string
---@field ok any
---@field result table
---@field step table

---@class CharacterizeSequence
---@field end_primer_length? number
---@field gate? any
---@field max_orf? number
---@field min_orf_aa? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class CharacterizeSequenceCreateData
---@field end_primer_length? number
---@field gate? any
---@field max_orf? number
---@field min_orf_aa? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class CloningSimulate
---@field arm_tm_target? number
---@field circular? boolean
---@field enzyme? string
---@field enzyme3? string
---@field enzyme5? string
---@field fragment? table
---@field gate? any
---@field insert? string
---@field method string
---@field name? table
---@field ok any
---@field overlap_len? number
---@field provenance table
---@field result table
---@field tool string
---@field vector? string

---@class CloningSimulateCreateData
---@field arm_tm_target? number
---@field circular? boolean
---@field enzyme? string
---@field enzyme3? string
---@field enzyme5? string
---@field fragment? table
---@field gate? any
---@field insert? string
---@field method string
---@field name? table
---@field ok any
---@field overlap_len? number
---@field provenance table
---@field result table
---@field tool string
---@field vector? string

---@class CodonAdaptationIndex
---@field frame_start? number
---@field gate? any
---@field ok any
---@field organism? string
---@field provenance table
---@field rare_threshold? number
---@field result table
---@field sequence string
---@field tool string

---@class CodonAdaptationIndexCreateData
---@field frame_start? number
---@field gate? any
---@field ok any
---@field organism? string
---@field provenance table
---@field rare_threshold? number
---@field result table
---@field sequence string
---@field tool string

---@class CodonOptimize
---@field gate? any
---@field ok any
---@field organism? string
---@field protein string
---@field provenance table
---@field result table
---@field tool string

---@class CodonOptimizeCreateData
---@field gate? any
---@field ok any
---@field organism? string
---@field protein string
---@field provenance table
---@field result table
---@field tool string

---@class ConstructAutofix
---@field avoid_enzyme? table
---@field cryptic_orf_min_aa? number
---@field frame_start? number
---@field gate? any
---@field gc_high? number
---@field gc_low? number
---@field gc_window? number
---@field homopolymer_min? number
---@field max_pass? number
---@field ok any
---@field organism? string
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ConstructAutofixCreateData
---@field avoid_enzyme? table
---@field cryptic_orf_min_aa? number
---@field frame_start? number
---@field gate? any
---@field gc_high? number
---@field gc_low? number
---@field gc_window? number
---@field homopolymer_min? number
---@field max_pass? number
---@field ok any
---@field organism? string
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ConstructQc
---@field avoid_enzyme? table
---@field cryptic_orf_min_aa? number
---@field frame_start? number
---@field gate? any
---@field gc_high? number
---@field gc_low? number
---@field gc_window? number
---@field homopolymer_min? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ConstructQcCreateData
---@field avoid_enzyme? table
---@field cryptic_orf_min_aa? number
---@field frame_start? number
---@field gate? any
---@field gc_high? number
---@field gc_low? number
---@field gc_window? number
---@field homopolymer_min? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class CrisprGrnaDesign
---@field gate? any
---@field min_score? number
---@field nuclease? string
---@field ok any
---@field provenance table
---@field result table
---@field search_reverse_strand? boolean
---@field sequence string
---@field tool string

---@class CrisprGrnaDesignCreateData
---@field gate? any
---@field min_score? number
---@field nuclease? string
---@field ok any
---@field provenance table
---@field result table
---@field search_reverse_strand? boolean
---@field sequence string
---@field tool string

---@class CrisprHdrDonor
---@field arm_length? number
---@field block_pam? boolean
---@field design_genotyping_primer? boolean
---@field edit_end? number
---@field edit_start? number
---@field frame_start? number
---@field gate? any
---@field guide_end? number
---@field guide_start? number
---@field guide_strand? string
---@field nuclease? string
---@field ok any
---@field provenance table
---@field replacement string
---@field result table
---@field target_sequence string
---@field tool string

---@class CrisprHdrDonorCreateData
---@field arm_length? number
---@field block_pam? boolean
---@field design_genotyping_primer? boolean
---@field edit_end? number
---@field edit_start? number
---@field frame_start? number
---@field gate? any
---@field guide_end? number
---@field guide_start? number
---@field guide_strand? string
---@field nuclease? string
---@field ok any
---@field provenance table
---@field replacement string
---@field result table
---@field target_sequence string
---@field tool string

---@class CrisprOfftargetCheck
---@field gate? any
---@field max_mismatch? number
---@field nuclease? string
---@field ok any
---@field protospacer string
---@field provenance table
---@field result table
---@field tool string

---@class CrisprOfftargetCheckCreateData
---@field gate? any
---@field max_mismatch? number
---@field nuclease? string
---@field ok any
---@field protospacer string
---@field provenance table
---@field result table
---@field tool string

---@class CrossDimer
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence_a string
---@field sequence_b string
---@field tool string

---@class CrossDimerCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence_a string
---@field sequence_b string
---@field tool string

---@class DnaMolarity
---@field gate? any
---@field length? number
---@field mass_ng? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence? string
---@field tool string
---@field type? string
---@field volume_ul? number

---@class DnaMolarityCreateData
---@field gate? any
---@field length? number
---@field mass_ng? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence? string
---@field tool string
---@field type? string
---@field volume_ul? number

---@class DoubleDigest
---@field enzyme_a string
---@field enzyme_b string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class DoubleDigestCreateData
---@field enzyme_a string
---@field enzyme_b string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class ExportEchoPicklist
---@field gate? any
---@field ok any
---@field provenance table
---@field reaction table
---@field result table
---@field tool string

---@class ExportEchoPicklistCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field reaction table
---@field result table
---@field tool string

---@class ExportOpentronsProtocol
---@field gate? any
---@field ok any
---@field protocol_name? string
---@field provenance table
---@field reaction table
---@field result table
---@field tool string

---@class ExportOpentronsProtocolCreateData
---@field gate? any
---@field ok any
---@field protocol_name? string
---@field provenance table
---@field reaction table
---@field result table
---@field tool string

---@class ExportPlateLayout
---@field gate? any
---@field ok any
---@field provenance table
---@field reaction table
---@field result table
---@field tool string

---@class ExportPlateLayoutCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field reaction table
---@field result table
---@field tool string

---@class ExpressionHeatmapCluster
---@field cluster_col? boolean
---@field cluster_row? boolean
---@field distance_metric? string
---@field gate? any
---@field gene table
---@field linkage? string
---@field ok any
---@field provenance table
---@field result table
---@field sample table
---@field tool string
---@field value table
---@field z_score_row? boolean

---@class ExpressionHeatmapClusterCreateData
---@field cluster_col? boolean
---@field cluster_row? boolean
---@field distance_metric? string
---@field gate? any
---@field gene table
---@field linkage? string
---@field ok any
---@field provenance table
---@field result table
---@field sample table
---@field tool string
---@field value table
---@field z_score_row? boolean

---@class FastqQcReport
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field quality_offset? number
---@field result table
---@field tool string

---@class FastqQcReportCreateData
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field quality_offset? number
---@field result table
---@field tool string

---@class FastqTrim
---@field gate? any
---@field input string
---@field min_length? number
---@field ok any
---@field provenance table
---@field quality_offset? number
---@field quality_threshold? number
---@field result table
---@field tool string

---@class FastqTrimCreateData
---@field gate? any
---@field input string
---@field min_length? number
---@field ok any
---@field provenance table
---@field quality_offset? number
---@field quality_threshold? number
---@field result table
---@field tool string

---@class FindOrf
---@field gate? any
---@field min_aa_length? number
---@field ok any
---@field provenance table
---@field require_stop? boolean
---@field result table
---@field sequence string
---@field tool string

---@class FindOrfCreateData
---@field gate? any
---@field min_aa_length? number
---@field ok any
---@field provenance table
---@field require_stop? boolean
---@field result table
---@field sequence string
---@field tool string

---@class FormatSequence
---@field case_mode? string
---@field convert? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field reverse? boolean
---@field sequence string
---@field strip_non_letter? boolean
---@field tool string
---@field width? number

---@class FormatSequenceCreateData
---@field case_mode? string
---@field convert? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field reverse? boolean
---@field sequence string
---@field strip_non_letter? boolean
---@field tool string
---@field width? number

---@class FunctionalEnrichment
---@field background? table
---@field collection? table
---@field gate? any
---@field gene table
---@field max_term_size? number
---@field min_term_size? number
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class FunctionalEnrichmentCreateData
---@field background? table
---@field collection? table
---@field gate? any
---@field gene table
---@field max_term_size? number
---@field min_term_size? number
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GcContent
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class GcContentCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class GeneDossier
---@field gate? any
---@field gene string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GeneDossierCreateData
---@field gate? any
---@field gene string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GeneExpression
---@field gate? any
---@field gene string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GeneExpressionCreateData
---@field gate? any
---@field gene string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GeneModel
---@field gate? any
---@field gene string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GeneModelCreateData
---@field gate? any
---@field gene string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GoldenGateFidelity
---@field compare_to_named_set? string
---@field dataset? string
---@field gate? any
---@field ok any
---@field overhang table
---@field provenance table
---@field result table
---@field risk_threshold? number
---@field tool string

---@class GoldenGateFidelityCreateData
---@field compare_to_named_set? string
---@field dataset? string
---@field gate? any
---@field ok any
---@field overhang table
---@field provenance table
---@field result table
---@field risk_threshold? number
---@field tool string

---@class HgvsConvert
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string
---@field variant string

---@class HgvsConvertCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string
---@field variant string

---@class IdMapPoll
---@field gate? any
---@field job_id string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class IdMapPollCreateData
---@field gate? any
---@field job_id string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class IdMapSubmit
---@field from string
---@field gate? any
---@field ids table
---@field ok any
---@field provenance table
---@field result table
---@field tax_id? string
---@field to string
---@field tool string

---@class IdMapSubmitCreateData
---@field from string
---@field gate? any
---@field ids table
---@field ok any
---@field provenance table
---@field result table
---@field tax_id? string
---@field to string
---@field tool string

---@class InSilicoPcr
---@field circular? boolean
---@field forward_primer string
---@field gate? any
---@field max_mismatch? number
---@field ok any
---@field provenance table
---@field result table
---@field reverse_primer string
---@field template string
---@field tool string

---@class InSilicoPcrCreateData
---@field circular? boolean
---@field forward_primer string
---@field gate? any
---@field max_mismatch? number
---@field ok any
---@field provenance table
---@field result table
---@field reverse_primer string
---@field template string
---@field tool string

---@class KaspPrimerDesign
---@field add_secondary_mismatch? boolean
---@field allele_a string
---@field allele_b string
---@field gate? any
---@field max_amplicon? number
---@field min_amplicon? number
---@field ok any
---@field provenance table
---@field result table
---@field snp_position number
---@field target string
---@field target_core_tm? number
---@field tool string

---@class KaspPrimerDesignCreateData
---@field add_secondary_mismatch? boolean
---@field allele_a string
---@field allele_b string
---@field gate? any
---@field max_amplicon? number
---@field min_amplicon? number
---@field ok any
---@field provenance table
---@field result table
---@field snp_position number
---@field target string
---@field target_core_tm? number
---@field tool string

---@class ListTool

---@class ListToolLoadMatch

---@class MeltingTemperature
---@field dntp_mm? number
---@field gate? any
---@field mg_mm? number
---@field na_mm? number
---@field ok any
---@field oligo_nm? number
---@field provenance table
---@field result table
---@field sequence string
---@field target_tm? number
---@field tm_tolerance? number
---@field tool string

---@class MeltingTemperatureCreateData
---@field dntp_mm? number
---@field gate? any
---@field mg_mm? number
---@field na_mm? number
---@field ok any
---@field oligo_nm? number
---@field provenance table
---@field result table
---@field sequence string
---@field target_tm? number
---@field tm_tolerance? number
---@field tool string

---@class MotifFinder
---@field gate? any
---@field max_mismatch? number
---@field motif string
---@field ok any
---@field provenance table
---@field result table
---@field search_reverse_strand? boolean
---@field sequence string
---@field tool string

---@class MotifFinderCreateData
---@field gate? any
---@field max_mismatch? number
---@field motif string
---@field ok any
---@field provenance table
---@field result table
---@field search_reverse_strand? boolean
---@field sequence string
---@field tool string

---@class MultipleSequenceAlignment
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class MultipleSequenceAlignmentCreateData
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class OligoAnalysi
---@field dntp_mm? number
---@field gate? any
---@field mg_mm? number
---@field na_mm? number
---@field ok any
---@field oligo_nm? number
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class OligoAnalysiCreateData
---@field dntp_mm? number
---@field gate? any
---@field mg_mm? number
---@field na_mm? number
---@field ok any
---@field oligo_nm? number
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class OrthologMap
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field source_species? string
---@field symbol table
---@field target_species string
---@field tool string
---@field type? string

---@class OrthologMapCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field source_species? string
---@field symbol table
---@field target_species string
---@field tool string
---@field type? string

---@class PairwiseAlignment
---@field gap? number
---@field gate? any
---@field match? number
---@field mismatch? number
---@field mode? string
---@field ok any
---@field provenance table
---@field result table
---@field seq_a string
---@field seq_b string
---@field tool string

---@class PairwiseAlignmentCreateData
---@field gap? number
---@field gate? any
---@field match? number
---@field mismatch? number
---@field mode? string
---@field ok any
---@field provenance table
---@field result table
---@field seq_a string
---@field seq_b string
---@field tool string

---@class ParseGenbank
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field text string
---@field tool string

---@class ParseGenbankCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field text string
---@field tool string

---@class ParseSangerTrace
---@field file_base64 string
---@field file_name? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class ParseSangerTraceCreateData
---@field file_base64 string
---@field file_name? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class PlasmidAnnotate
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class PlasmidAnnotateCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class PlasmidDeepAnnotate
---@field circular? boolean
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class PlasmidDeepAnnotateCreateData
---@field circular? boolean
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class PlasmidFullReport
---@field circular? boolean
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string
---@field top_n? number

---@class PlasmidFullReportCreateData
---@field circular? boolean
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string
---@field top_n? number

---@class PlasmidIdentify
---@field circular? boolean
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string
---@field top_n? number

---@class PlasmidIdentifyCreateData
---@field circular? boolean
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string
---@field top_n? number

---@class PrimeEditingDesign
---@field edit_end number
---@field edit_start number
---@field frame_start? number
---@field gate? any
---@field inserted_seq? string
---@field ok any
---@field pbs_length? number
---@field provenance table
---@field result table
---@field rtt_homology? number
---@field target string
---@field tool string

---@class PrimeEditingDesignCreateData
---@field edit_end number
---@field edit_start number
---@field frame_start? number
---@field gate? any
---@field inserted_seq? string
---@field ok any
---@field pbs_length? number
---@field provenance table
---@field result table
---@field rtt_homology? number
---@field target string
---@field tool string

---@class PrimeEditingTwinDesign
---@field gate? any
---@field new_sequence string
---@field ok any
---@field overlap_length? number
---@field pbs_length? number
---@field provenance table
---@field replace_end number
---@field replace_start number
---@field result table
---@field target string
---@field tool string

---@class PrimeEditingTwinDesignCreateData
---@field gate? any
---@field new_sequence string
---@field ok any
---@field overlap_length? number
---@field pbs_length? number
---@field provenance table
---@field replace_end number
---@field replace_start number
---@field result table
---@field target string
---@field tool string

---@class PrimerDesign
---@field amplicon_max? number
---@field amplicon_min? number
---@field dntp_mm? number
---@field gate? any
---@field gc_max? number
---@field gc_min? number
---@field len_max? number
---@field len_min? number
---@field len_opt? number
---@field max_return? number
---@field mg_mm? number
---@field na_mm? number
---@field ok any
---@field oligo_nm? number
---@field provenance table
---@field result table
---@field target_end? number
---@field target_start? number
---@field template string
---@field tm_max? number
---@field tm_max_diff? number
---@field tm_min? number
---@field tm_opt? number
---@field tool string

---@class PrimerDesignCreateData
---@field amplicon_max? number
---@field amplicon_min? number
---@field dntp_mm? number
---@field gate? any
---@field gc_max? number
---@field gc_min? number
---@field len_max? number
---@field len_min? number
---@field len_opt? number
---@field max_return? number
---@field mg_mm? number
---@field na_mm? number
---@field ok any
---@field oligo_nm? number
---@field provenance table
---@field result table
---@field target_end? number
---@field target_start? number
---@field template string
---@field tm_max? number
---@field tm_max_diff? number
---@field tm_min? number
---@field tm_opt? number
---@field tool string

---@class PrimerSpecificity
---@field forward_primer string
---@field gate? any
---@field max_mismatch? number
---@field max_product_length? number
---@field ok any
---@field provenance table
---@field result table
---@field reverse_primer string
---@field tool string

---@class PrimerSpecificityCreateData
---@field forward_primer string
---@field gate? any
---@field max_mismatch? number
---@field max_product_length? number
---@field ok any
---@field provenance table
---@field result table
---@field reverse_primer string
---@field tool string

---@class ProteaseDigestion
---@field gate? any
---@field max_mass? number
---@field max_peptide? number
---@field min_mass? number
---@field missed_cleavage? number
---@field ok any
---@field protease? string
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ProteaseDigestionCreateData
---@field gate? any
---@field max_mass? number
---@field max_peptide? number
---@field min_mass? number
---@field missed_cleavage? number
---@field ok any
---@field protease? string
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ProteinAnnotatePoll
---@field gate? any
---@field job_id string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class ProteinAnnotatePollCreateData
---@field gate? any
---@field job_id string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class ProteinAnnotateSubmit
---@field appl? string
---@field gate? any
---@field goterm? boolean
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ProteinAnnotateSubmitCreateData
---@field appl? string
---@field gate? any
---@field goterm? boolean
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ProteinHydrophobicity
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field scale? string
---@field sequence string
---@field tool string
---@field window? number

---@class ProteinHydrophobicityCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field scale? string
---@field sequence string
---@field tool string
---@field window? number

---@class ProteinProperty
---@field charge_step? number
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ProteinPropertyCreateData
---@field charge_step? number
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class RandomSequence
---@field gate? any
---@field gc_content? number
---@field kind? string
---@field length number
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class RandomSequenceCreateData
---@field gate? any
---@field gc_content? number
---@field kind? string
---@field length number
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class RestrictionSite
---@field enzyme? table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class RestrictionSiteCreateData
---@field enzyme? table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ReverseComplement
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string
---@field type? string

---@class ReverseComplementCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string
---@field type? string

---@class ReverseTranslate
---@field gate? any
---@field mode? string
---@field ok any
---@field organism? string
---@field protein string
---@field provenance table
---@field result table
---@field tool string

---@class ReverseTranslateCreateData
---@field gate? any
---@field mode? string
---@field ok any
---@field organism? string
---@field protein string
---@field provenance table
---@field result table
---@field tool string

---@class RnaFold
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class RnaFoldCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class SangerVsReference
---@field file_base64? string
---@field file_name? string
---@field gate? any
---@field min_coverage? number
---@field ok any
---@field provenance table
---@field read? string
---@field reference string
---@field result table
---@field tool string

---@class SangerVsReferenceCreateData
---@field file_base64? string
---@field file_name? string
---@field gate? any
---@field min_coverage? number
---@field ok any
---@field provenance table
---@field read? string
---@field reference string
---@field result table
---@field tool string

---@class SavePermalink
---@field arg table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class SavePermalinkCreateData
---@field arg table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class SeqfileStat
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field quality_offset? number
---@field result table
---@field tool string

---@class SeqfileStatCreateData
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field quality_offset? number
---@field result table
---@field tool string

---@class SequenceFetch
---@field accession string
---@field db? string
---@field format? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class SequenceFetchCreateData
---@field accession string
---@field db? string
---@field format? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class SequenceFormatConvert
---@field from? string
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field result table
---@field to? string
---@field tool string

---@class SequenceFormatConvertCreateData
---@field from? string
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field result table
---@field to? string
---@field tool string

---@class SequenceReport
---@field end_primer_length? number
---@field gate? any
---@field max_orf? number
---@field min_orf_aa? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class SequenceReportCreateData
---@field end_primer_length? number
---@field gate? any
---@field max_orf? number
---@field min_orf_aa? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class SequenceSearch
---@field db? string
---@field gate? any
---@field gene? string
---@field max_result? number
---@field ok any
---@field organism? string
---@field provenance table
---@field result table
---@field term? string
---@field tool string

---@class SequenceSearchCreateData
---@field db? string
---@field gate? any
---@field gene? string
---@field max_result? number
---@field ok any
---@field organism? string
---@field provenance table
---@field result table
---@field term? string
---@field tool string

---@class SequencingReadbackVerify
---@field gate? any
---@field min_supporting_read? number
---@field ok any
---@field provenance table
---@field read string
---@field reference string
---@field result table
---@field tool string

---@class SequencingReadbackVerifyCreateData
---@field gate? any
---@field min_supporting_read? number
---@field ok any
---@field provenance table
---@field read string
---@field reference string
---@field result table
---@field tool string

---@class SessionCreate
---@field entry? table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class SessionCreateCreateData
---@field entry? table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class SessionGet
---@field gate? any
---@field name? table
---@field ok any
---@field provenance table
---@field result table
---@field session_id string
---@field tool string

---@class SessionGetCreateData
---@field gate? any
---@field name? table
---@field ok any
---@field provenance table
---@field result table
---@field session_id string
---@field tool string

---@class SessionRun
---@field arg? table
---@field from_session? table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field session_id string
---@field tool string
---@field write_back? table

---@class SessionRunCreateData
---@field arg? table
---@field from_session? table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field session_id string
---@field tool string
---@field write_back? table

---@class SessionSet
---@field entry table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field session_id string
---@field tool string

---@class SessionSetCreateData
---@field entry table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field session_id string
---@field tool string

---@class SirnaDesign
---@field gate? any
---@field min_reynold? number
---@field ok any
---@field provenance table
---@field result table
---@field sh_rna_loop? string
---@field target string
---@field tool string

---@class SirnaDesignCreateData
---@field gate? any
---@field min_reynold? number
---@field ok any
---@field provenance table
---@field result table
---@field sh_rna_loop? string
---@field target string
---@field tool string

---@class SiteDirectedMutagenesi
---@field arm_tm_target? number
---@field dntp_mm? number
---@field edit_kind? string
---@field frame_start? number
---@field gate? any
---@field mg_mm? number
---@field na_mm? number
---@field new_base? string
---@field ok any
---@field oligo_nm? number
---@field organism? string
---@field position? number
---@field provenance table
---@field residue? number
---@field result table
---@field style? string
---@field target_aa? string
---@field template string
---@field tool string

---@class SiteDirectedMutagenesiCreateData
---@field arm_tm_target? number
---@field dntp_mm? number
---@field edit_kind? string
---@field frame_start? number
---@field gate? any
---@field mg_mm? number
---@field na_mm? number
---@field new_base? string
---@field ok any
---@field oligo_nm? number
---@field organism? string
---@field position? number
---@field provenance table
---@field residue? number
---@field result table
---@field style? string
---@field target_aa? string
---@field template string
---@field tool string

---@class Translate
---@field frame? number
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field to_stop? boolean
---@field tool string

---@class TranslateCreateData
---@field frame? number
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field to_stop? boolean
---@field tool string

---@class VariantAnnotate
---@field assembly? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string
---@field variant string

---@class VariantAnnotateCreateData
---@field assembly? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string
---@field variant string

---@class VariantComparator
---@field coding? boolean
---@field frame_start? number
---@field gate? any
---@field ok any
---@field provenance table
---@field query string
---@field reference string
---@field result table
---@field tool string

---@class VariantComparatorCreateData
---@field coding? boolean
---@field frame_start? number
---@field gate? any
---@field ok any
---@field provenance table
---@field query string
---@field reference string
---@field result table
---@field tool string

---@class VerifyAssembly
---@field arm_tm_target? number
---@field circular? boolean
---@field claimed_construct string
---@field coding? boolean
---@field enzyme? string
---@field enzyme3? string
---@field enzyme5? string
---@field fragment? table
---@field fragment_pcr? table
---@field frame_start? number
---@field gate? any
---@field insert? string
---@field insert_pcr? table
---@field method string
---@field name? table
---@field ok any
---@field overlap_len? number
---@field provenance table
---@field result table
---@field tool string
---@field vector? string
---@field vector_pcr? table

---@class VerifyAssemblyCreateData
---@field arm_tm_target? number
---@field circular? boolean
---@field claimed_construct string
---@field coding? boolean
---@field enzyme? string
---@field enzyme3? string
---@field enzyme5? string
---@field fragment? table
---@field fragment_pcr? table
---@field frame_start? number
---@field gate? any
---@field insert? string
---@field insert_pcr? table
---@field method string
---@field name? table
---@field ok any
---@field overlap_len? number
---@field provenance table
---@field result table
---@field tool string
---@field vector? string
---@field vector_pcr? table

---@class VerifyConstruct
---@field claimed_construct string
---@field expected_frame_start? number
---@field gate? any
---@field insert_forward_primer string
---@field insert_reverse_primer string
---@field insert_template string
---@field max_primer_mismatch? number
---@field ok any
---@field provenance table
---@field result table
---@field template_circular? boolean
---@field tool string

---@class VerifyConstructCreateData
---@field claimed_construct string
---@field expected_frame_start? number
---@field gate? any
---@field insert_forward_primer string
---@field insert_reverse_primer string
---@field insert_template string
---@field max_primer_mismatch? number
---@field ok any
---@field provenance table
---@field result table
---@field template_circular? boolean
---@field tool string

---@class VirtualGel
---@field circular? boolean
---@field enzyme? table
---@field gate? any
---@field ladder? string
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class VirtualGelCreateData
---@field circular? boolean
---@field enzyme? table
---@field gate? any
---@field ladder? string
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class VolcanoPlotData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field row table
---@field tool string

---@class VolcanoPlotDataCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field row table
---@field tool string

---@class WebSearch
---@field gate? any
---@field max_result? number
---@field ok any
---@field provenance table
---@field query string
---@field result table
---@field tool string

---@class WebSearchCreateData
---@field gate? any
---@field max_result? number
---@field ok any
---@field provenance table
---@field query string
---@field result table
---@field tool string

local M = {}

return M
