-- Typed models for the SeqbenchMcp SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class AlphafoldLookup
---@field accession string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class AlphafoldLookupCreateData
---@field accession string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class AsoDesign
---@field gate? any
---@field length? number
---@field ok any
---@field provenance table
---@field result table
---@field target string
---@field tool string
---@field wing? number

---@class AsoDesignCreateData
---@field gate? any
---@field length? number
---@field ok any
---@field provenance table
---@field result table
---@field target string
---@field tool string
---@field wing? number

---@class BaseEditingDesign
---@field editor? string
---@field frameStart? number
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field target string
---@field targetPosition? number
---@field tool string

---@class BaseEditingDesignCreateData
---@field editor? string
---@field frameStart? number
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field target string
---@field targetPosition? number
---@field tool string

---@class Batch
---@field args? table
---@field capped boolean
---@field columns table
---@field count number
---@field errors number
---@field input string
---@field limit number
---@field provenance table
---@field rows table
---@field tool string

---@class BatchLoadMatch
---@field args? table
---@field capped? boolean
---@field columns? table
---@field count? number
---@field errors? number
---@field input? string
---@field limit? number
---@field provenance? table
---@field rows? table
---@field tool? string

---@class BatchCreateData
---@field args? table
---@field capped boolean
---@field columns table
---@field count number
---@field errors number
---@field input string
---@field limit number
---@field provenance table
---@field rows table
---@field tool string

---@class BatchWorkflow
---@field capped boolean
---@field columns table
---@field count number
---@field errors number
---@field input string
---@field limit number
---@field provenance table
---@field rows table
---@field steps table

---@class BatchWorkflowLoadMatch
---@field capped? boolean
---@field columns? table
---@field count? number
---@field errors? number
---@field input? string
---@field limit? number
---@field provenance? table
---@field rows? table
---@field steps? table

---@class BatchWorkflowCreateData
---@field capped boolean
---@field columns table
---@field count number
---@field errors number
---@field input string
---@field limit number
---@field provenance table
---@field rows table
---@field steps table

---@class CharacterizeSequence
---@field endPrimerLength? number
---@field gate? any
---@field maxOrfs? number
---@field minOrfAa? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class CharacterizeSequenceCreateData
---@field endPrimerLength? number
---@field gate? any
---@field maxOrfs? number
---@field minOrfAa? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class CloningSimulate
---@field armTmTarget? number
---@field circular? boolean
---@field enzyme? string
---@field enzyme3? string
---@field enzyme5? string
---@field fragments? table
---@field gate? any
---@field insert? string
---@field method string
---@field names? table
---@field ok any
---@field overlapLen? number
---@field provenance table
---@field result table
---@field tool string
---@field vector? string

---@class CloningSimulateCreateData
---@field armTmTarget? number
---@field circular? boolean
---@field enzyme? string
---@field enzyme3? string
---@field enzyme5? string
---@field fragments? table
---@field gate? any
---@field insert? string
---@field method string
---@field names? table
---@field ok any
---@field overlapLen? number
---@field provenance table
---@field result table
---@field tool string
---@field vector? string

---@class CodonAdaptationIndex
---@field frameStart? number
---@field gate? any
---@field ok any
---@field organism? string
---@field provenance table
---@field rareThreshold? number
---@field result table
---@field sequence string
---@field tool string

---@class CodonAdaptationIndexCreateData
---@field frameStart? number
---@field gate? any
---@field ok any
---@field organism? string
---@field provenance table
---@field rareThreshold? number
---@field result table
---@field sequence string
---@field tool string

---@class CodonOptimize
---@field gate? any
---@field ok any
---@field organism? string
---@field protein string
---@field provenance table
---@field result table
---@field tool string

---@class CodonOptimizeCreateData
---@field gate? any
---@field ok any
---@field organism? string
---@field protein string
---@field provenance table
---@field result table
---@field tool string

---@class ConstructAutofix
---@field avoidEnzymes? table
---@field crypticOrfMinAa? number
---@field frameStart? number
---@field gate? any
---@field gcHigh? number
---@field gcLow? number
---@field gcWindow? number
---@field homopolymerMin? number
---@field maxPasses? number
---@field ok any
---@field organism? string
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ConstructAutofixCreateData
---@field avoidEnzymes? table
---@field crypticOrfMinAa? number
---@field frameStart? number
---@field gate? any
---@field gcHigh? number
---@field gcLow? number
---@field gcWindow? number
---@field homopolymerMin? number
---@field maxPasses? number
---@field ok any
---@field organism? string
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ConstructQc
---@field avoidEnzymes? table
---@field crypticOrfMinAa? number
---@field frameStart? number
---@field gate? any
---@field gcHigh? number
---@field gcLow? number
---@field gcWindow? number
---@field homopolymerMin? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ConstructQcCreateData
---@field avoidEnzymes? table
---@field crypticOrfMinAa? number
---@field frameStart? number
---@field gate? any
---@field gcHigh? number
---@field gcLow? number
---@field gcWindow? number
---@field homopolymerMin? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class CrisprGrnaDesign
---@field gate? any
---@field minScore? number
---@field nuclease? string
---@field ok any
---@field provenance table
---@field result table
---@field searchReverseStrand? boolean
---@field sequence string
---@field tool string

---@class CrisprGrnaDesignCreateData
---@field gate? any
---@field minScore? number
---@field nuclease? string
---@field ok any
---@field provenance table
---@field result table
---@field searchReverseStrand? boolean
---@field sequence string
---@field tool string

---@class CrisprHdrDonor
---@field armLength? number
---@field blockPam? boolean
---@field designGenotypingPrimers? boolean
---@field editEnd? number
---@field editStart? number
---@field frameStart? number
---@field gate? any
---@field guideEnd? number
---@field guideStart? number
---@field guideStrand? string
---@field nuclease? string
---@field ok any
---@field provenance table
---@field replacement string
---@field result table
---@field targetSequence string
---@field tool string

---@class CrisprHdrDonorCreateData
---@field armLength? number
---@field blockPam? boolean
---@field designGenotypingPrimers? boolean
---@field editEnd? number
---@field editStart? number
---@field frameStart? number
---@field gate? any
---@field guideEnd? number
---@field guideStart? number
---@field guideStrand? string
---@field nuclease? string
---@field ok any
---@field provenance table
---@field replacement string
---@field result table
---@field targetSequence string
---@field tool string

---@class CrisprOfftargetCheck
---@field gate? any
---@field maxMismatches? number
---@field nuclease? string
---@field ok any
---@field protospacer string
---@field provenance table
---@field result table
---@field tool string

---@class CrisprOfftargetCheckCreateData
---@field gate? any
---@field maxMismatches? number
---@field nuclease? string
---@field ok any
---@field protospacer string
---@field provenance table
---@field result table
---@field tool string

---@class CrossDimer
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequenceA string
---@field sequenceB string
---@field tool string

---@class CrossDimerCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequenceA string
---@field sequenceB string
---@field tool string

---@class DnaMolarity
---@field gate? any
---@field length? number
---@field massNg? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence? string
---@field tool string
---@field type? string
---@field volumeUl? number

---@class DnaMolarityCreateData
---@field gate? any
---@field length? number
---@field massNg? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence? string
---@field tool string
---@field type? string
---@field volumeUl? number

---@class DoubleDigest
---@field enzymeA string
---@field enzymeB string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class DoubleDigestCreateData
---@field enzymeA string
---@field enzymeB string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class ExportEchoPicklist
---@field gate? any
---@field ok any
---@field provenance table
---@field reactions table
---@field result table
---@field tool string

---@class ExportEchoPicklistCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field reactions table
---@field result table
---@field tool string

---@class ExportOpentronsProtocol
---@field gate? any
---@field ok any
---@field protocolName? string
---@field provenance table
---@field reactions table
---@field result table
---@field tool string

---@class ExportOpentronsProtocolCreateData
---@field gate? any
---@field ok any
---@field protocolName? string
---@field provenance table
---@field reactions table
---@field result table
---@field tool string

---@class ExportPlateLayout
---@field gate? any
---@field ok any
---@field provenance table
---@field reactions table
---@field result table
---@field tool string

---@class ExportPlateLayoutCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field reactions table
---@field result table
---@field tool string

---@class ExpressionHeatmapCluster
---@field clusterCols? boolean
---@field clusterRows? boolean
---@field distanceMetric? string
---@field gate? any
---@field genes table
---@field linkage? string
---@field ok any
---@field provenance table
---@field result table
---@field samples table
---@field tool string
---@field values table
---@field zScoreRows? boolean

---@class ExpressionHeatmapClusterCreateData
---@field clusterCols? boolean
---@field clusterRows? boolean
---@field distanceMetric? string
---@field gate? any
---@field genes table
---@field linkage? string
---@field ok any
---@field provenance table
---@field result table
---@field samples table
---@field tool string
---@field values table
---@field zScoreRows? boolean

---@class FastqQcReport
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field qualityOffset? number
---@field result table
---@field tool string

---@class FastqQcReportCreateData
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field qualityOffset? number
---@field result table
---@field tool string

---@class FastqTrim
---@field gate? any
---@field input string
---@field minLength? number
---@field ok any
---@field provenance table
---@field qualityOffset? number
---@field qualityThreshold? number
---@field result table
---@field tool string

---@class FastqTrimCreateData
---@field gate? any
---@field input string
---@field minLength? number
---@field ok any
---@field provenance table
---@field qualityOffset? number
---@field qualityThreshold? number
---@field result table
---@field tool string

---@class FindOrf
---@field gate? any
---@field minAaLength? number
---@field ok any
---@field provenance table
---@field requireStop? boolean
---@field result table
---@field sequence string
---@field tool string

---@class FindOrfCreateData
---@field gate? any
---@field minAaLength? number
---@field ok any
---@field provenance table
---@field requireStop? boolean
---@field result table
---@field sequence string
---@field tool string

---@class FormatSequence
---@field caseMode? string
---@field convert? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field reverse? boolean
---@field sequence string
---@field stripNonLetters? boolean
---@field tool string
---@field width? number

---@class FormatSequenceCreateData
---@field caseMode? string
---@field convert? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field reverse? boolean
---@field sequence string
---@field stripNonLetters? boolean
---@field tool string
---@field width? number

---@class FunctionalEnrichment
---@field background? table
---@field collections? table
---@field gate? any
---@field genes table
---@field maxTermSize? number
---@field minTermSize? number
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class FunctionalEnrichmentCreateData
---@field background? table
---@field collections? table
---@field gate? any
---@field genes table
---@field maxTermSize? number
---@field minTermSize? number
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GcContent
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class GcContentCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class GeneDossier
---@field gate? any
---@field gene string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GeneDossierCreateData
---@field gate? any
---@field gene string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GeneExpression
---@field gate? any
---@field gene string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GeneExpressionCreateData
---@field gate? any
---@field gene string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GeneModel
---@field gate? any
---@field gene string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GeneModelCreateData
---@field gate? any
---@field gene string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class GoldenGateFidelity
---@field compareToNamedSet? string
---@field dataset? string
---@field gate? any
---@field ok any
---@field overhangs table
---@field provenance table
---@field result table
---@field riskThreshold? number
---@field tool string

---@class GoldenGateFidelityCreateData
---@field compareToNamedSet? string
---@field dataset? string
---@field gate? any
---@field ok any
---@field overhangs table
---@field provenance table
---@field result table
---@field riskThreshold? number
---@field tool string

---@class HgvsConvert
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string
---@field variant string

---@class HgvsConvertCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string
---@field variant string

---@class IdMapPoll
---@field gate? any
---@field jobId string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class IdMapPollCreateData
---@field gate? any
---@field jobId string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class IdMapSubmit
---@field from string
---@field gate? any
---@field ids table
---@field ok any
---@field provenance table
---@field result table
---@field taxId? string
---@field to string
---@field tool string

---@class IdMapSubmitCreateData
---@field from string
---@field gate? any
---@field ids table
---@field ok any
---@field provenance table
---@field result table
---@field taxId? string
---@field to string
---@field tool string

---@class InSilicoPcr
---@field circular? boolean
---@field forwardPrimer string
---@field gate? any
---@field maxMismatches? number
---@field ok any
---@field provenance table
---@field result table
---@field reversePrimer string
---@field template string
---@field tool string

---@class InSilicoPcrCreateData
---@field circular? boolean
---@field forwardPrimer string
---@field gate? any
---@field maxMismatches? number
---@field ok any
---@field provenance table
---@field result table
---@field reversePrimer string
---@field template string
---@field tool string

---@class KaspPrimerDesign
---@field addSecondaryMismatch? boolean
---@field alleleA string
---@field alleleB string
---@field gate? any
---@field maxAmplicon? number
---@field minAmplicon? number
---@field ok any
---@field provenance table
---@field result table
---@field snpPosition number
---@field target string
---@field targetCoreTm? number
---@field tool string

---@class KaspPrimerDesignCreateData
---@field addSecondaryMismatch? boolean
---@field alleleA string
---@field alleleB string
---@field gate? any
---@field maxAmplicon? number
---@field minAmplicon? number
---@field ok any
---@field provenance table
---@field result table
---@field snpPosition number
---@field target string
---@field targetCoreTm? number
---@field tool string

---@class ListTool

---@class ListToolLoadMatch

---@class MeltingTemperature
---@field dntpMM? number
---@field gate? any
---@field mgMM? number
---@field naMM? number
---@field ok any
---@field oligoNM? number
---@field provenance table
---@field result table
---@field sequence string
---@field targetTm? number
---@field tmTolerance? number
---@field tool string

---@class MeltingTemperatureCreateData
---@field dntpMM? number
---@field gate? any
---@field mgMM? number
---@field naMM? number
---@field ok any
---@field oligoNM? number
---@field provenance table
---@field result table
---@field sequence string
---@field targetTm? number
---@field tmTolerance? number
---@field tool string

---@class MotifFinder
---@field gate? any
---@field maxMismatches? number
---@field motif string
---@field ok any
---@field provenance table
---@field result table
---@field searchReverseStrand? boolean
---@field sequence string
---@field tool string

---@class MotifFinderCreateData
---@field gate? any
---@field maxMismatches? number
---@field motif string
---@field ok any
---@field provenance table
---@field result table
---@field searchReverseStrand? boolean
---@field sequence string
---@field tool string

---@class MultipleSequenceAlignment
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class MultipleSequenceAlignmentCreateData
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class OligoAnalysi
---@field dntpMM? number
---@field gate? any
---@field mgMM? number
---@field naMM? number
---@field ok any
---@field oligoNM? number
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class OligoAnalysiCreateData
---@field dntpMM? number
---@field gate? any
---@field mgMM? number
---@field naMM? number
---@field ok any
---@field oligoNM? number
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class OrthologMap
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sourceSpecies? string
---@field symbols table
---@field targetSpecies string
---@field tool string
---@field type? string

---@class OrthologMapCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sourceSpecies? string
---@field symbols table
---@field targetSpecies string
---@field tool string
---@field type? string

---@class PairwiseAlignment
---@field gap? number
---@field gate? any
---@field match? number
---@field mismatch? number
---@field mode? string
---@field ok any
---@field provenance table
---@field result table
---@field seqA string
---@field seqB string
---@field tool string

---@class PairwiseAlignmentCreateData
---@field gap? number
---@field gate? any
---@field match? number
---@field mismatch? number
---@field mode? string
---@field ok any
---@field provenance table
---@field result table
---@field seqA string
---@field seqB string
---@field tool string

---@class ParseGenbank
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field text string
---@field tool string

---@class ParseGenbankCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field text string
---@field tool string

---@class ParseSangerTrace
---@field fileBase64 string
---@field fileName? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class ParseSangerTraceCreateData
---@field fileBase64 string
---@field fileName? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class PlasmidAnnotate
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class PlasmidAnnotateCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class PlasmidDeepAnnotate
---@field circular? boolean
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class PlasmidDeepAnnotateCreateData
---@field circular? boolean
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class PlasmidFullReport
---@field circular? boolean
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string
---@field topN? number

---@class PlasmidFullReportCreateData
---@field circular? boolean
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string
---@field topN? number

---@class PlasmidIdentify
---@field circular? boolean
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string
---@field topN? number

---@class PlasmidIdentifyCreateData
---@field circular? boolean
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string
---@field topN? number

---@class PrimeEditingDesign
---@field editEnd number
---@field editStart number
---@field frameStart? number
---@field gate? any
---@field insertedSeq? string
---@field ok any
---@field pbsLength? number
---@field provenance table
---@field result table
---@field rttHomology? number
---@field target string
---@field tool string

---@class PrimeEditingDesignCreateData
---@field editEnd number
---@field editStart number
---@field frameStart? number
---@field gate? any
---@field insertedSeq? string
---@field ok any
---@field pbsLength? number
---@field provenance table
---@field result table
---@field rttHomology? number
---@field target string
---@field tool string

---@class PrimeEditingTwinDesign
---@field gate? any
---@field newSequence string
---@field ok any
---@field overlapLength? number
---@field pbsLength? number
---@field provenance table
---@field replaceEnd number
---@field replaceStart number
---@field result table
---@field target string
---@field tool string

---@class PrimeEditingTwinDesignCreateData
---@field gate? any
---@field newSequence string
---@field ok any
---@field overlapLength? number
---@field pbsLength? number
---@field provenance table
---@field replaceEnd number
---@field replaceStart number
---@field result table
---@field target string
---@field tool string

---@class PrimerDesign
---@field ampliconMax? number
---@field ampliconMin? number
---@field dntpMM? number
---@field gate? any
---@field gcMax? number
---@field gcMin? number
---@field lenMax? number
---@field lenMin? number
---@field lenOpt? number
---@field maxReturn? number
---@field mgMM? number
---@field naMM? number
---@field ok any
---@field oligoNM? number
---@field provenance table
---@field result table
---@field targetEnd? number
---@field targetStart? number
---@field template string
---@field tmMax? number
---@field tmMaxDiff? number
---@field tmMin? number
---@field tmOpt? number
---@field tool string

---@class PrimerDesignCreateData
---@field ampliconMax? number
---@field ampliconMin? number
---@field dntpMM? number
---@field gate? any
---@field gcMax? number
---@field gcMin? number
---@field lenMax? number
---@field lenMin? number
---@field lenOpt? number
---@field maxReturn? number
---@field mgMM? number
---@field naMM? number
---@field ok any
---@field oligoNM? number
---@field provenance table
---@field result table
---@field targetEnd? number
---@field targetStart? number
---@field template string
---@field tmMax? number
---@field tmMaxDiff? number
---@field tmMin? number
---@field tmOpt? number
---@field tool string

---@class PrimerSpecificity
---@field forwardPrimer string
---@field gate? any
---@field maxMismatches? number
---@field maxProductLength? number
---@field ok any
---@field provenance table
---@field result table
---@field reversePrimer string
---@field tool string

---@class PrimerSpecificityCreateData
---@field forwardPrimer string
---@field gate? any
---@field maxMismatches? number
---@field maxProductLength? number
---@field ok any
---@field provenance table
---@field result table
---@field reversePrimer string
---@field tool string

---@class ProteaseDigestion
---@field gate? any
---@field maxMass? number
---@field maxPeptides? number
---@field minMass? number
---@field missedCleavages? number
---@field ok any
---@field protease? string
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ProteaseDigestionCreateData
---@field gate? any
---@field maxMass? number
---@field maxPeptides? number
---@field minMass? number
---@field missedCleavages? number
---@field ok any
---@field protease? string
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ProteinAnnotatePoll
---@field gate? any
---@field jobId string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class ProteinAnnotatePollCreateData
---@field gate? any
---@field jobId string
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class ProteinAnnotateSubmit
---@field appl? string
---@field gate? any
---@field goterms? boolean
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ProteinAnnotateSubmitCreateData
---@field appl? string
---@field gate? any
---@field goterms? boolean
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ProteinHydrophobicity
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field scale? string
---@field sequence string
---@field tool string
---@field window? number

---@class ProteinHydrophobicityCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field scale? string
---@field sequence string
---@field tool string
---@field window? number

---@class ProteinProperty
---@field chargeStep? number
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ProteinPropertyCreateData
---@field chargeStep? number
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class RandomSequence
---@field gate? any
---@field gcContent? number
---@field kind? string
---@field length number
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class RandomSequenceCreateData
---@field gate? any
---@field gcContent? number
---@field kind? string
---@field length number
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class RestrictionSite
---@field enzymes? table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class RestrictionSiteCreateData
---@field enzymes? table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class ReverseComplement
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string
---@field type? string

---@class ReverseComplementCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string
---@field type? string

---@class ReverseTranslate
---@field gate? any
---@field mode? string
---@field ok any
---@field organism? string
---@field protein string
---@field provenance table
---@field result table
---@field tool string

---@class ReverseTranslateCreateData
---@field gate? any
---@field mode? string
---@field ok any
---@field organism? string
---@field protein string
---@field provenance table
---@field result table
---@field tool string

---@class RnaFold
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class RnaFoldCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class SangerVsReference
---@field fileBase64? string
---@field fileName? string
---@field gate? any
---@field minCoverage? number
---@field ok any
---@field provenance table
---@field read? string
---@field reference string
---@field result table
---@field tool string

---@class SangerVsReferenceCreateData
---@field fileBase64? string
---@field fileName? string
---@field gate? any
---@field minCoverage? number
---@field ok any
---@field provenance table
---@field read? string
---@field reference string
---@field result table
---@field tool string

---@class SavePermalink
---@field args table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class SavePermalinkCreateData
---@field args table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class SeqfileStat
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field qualityOffset? number
---@field result table
---@field tool string

---@class SeqfileStatCreateData
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field qualityOffset? number
---@field result table
---@field tool string

---@class SequenceFetch
---@field accession string
---@field db? string
---@field format? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class SequenceFetchCreateData
---@field accession string
---@field db? string
---@field format? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class SequenceFormatConvert
---@field from? string
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field result table
---@field to? string
---@field tool string

---@class SequenceFormatConvertCreateData
---@field from? string
---@field gate? any
---@field input string
---@field ok any
---@field provenance table
---@field result table
---@field to? string
---@field tool string

---@class SequenceReport
---@field endPrimerLength? number
---@field gate? any
---@field maxOrfs? number
---@field minOrfAa? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class SequenceReportCreateData
---@field endPrimerLength? number
---@field gate? any
---@field maxOrfs? number
---@field minOrfAa? number
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class SequenceSearch
---@field db? string
---@field gate? any
---@field gene? string
---@field maxResults? number
---@field ok any
---@field organism? string
---@field provenance table
---@field result table
---@field term? string
---@field tool string

---@class SequenceSearchCreateData
---@field db? string
---@field gate? any
---@field gene? string
---@field maxResults? number
---@field ok any
---@field organism? string
---@field provenance table
---@field result table
---@field term? string
---@field tool string

---@class SequencingReadbackVerify
---@field gate? any
---@field minSupportingReads? number
---@field ok any
---@field provenance table
---@field reads string
---@field reference string
---@field result table
---@field tool string

---@class SequencingReadbackVerifyCreateData
---@field gate? any
---@field minSupportingReads? number
---@field ok any
---@field provenance table
---@field reads string
---@field reference string
---@field result table
---@field tool string

---@class SessionCreate
---@field entries? table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class SessionCreateCreateData
---@field entries? table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string

---@class SessionGet
---@field gate? any
---@field names? table
---@field ok any
---@field provenance table
---@field result table
---@field sessionId string
---@field tool string

---@class SessionGetCreateData
---@field gate? any
---@field names? table
---@field ok any
---@field provenance table
---@field result table
---@field sessionId string
---@field tool string

---@class SessionRun
---@field args? table
---@field fromSession? table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sessionId string
---@field tool string
---@field writeBack? table

---@class SessionRunCreateData
---@field args? table
---@field fromSession? table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sessionId string
---@field tool string
---@field writeBack? table

---@class SessionSet
---@field entries table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sessionId string
---@field tool string

---@class SessionSetCreateData
---@field entries table
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sessionId string
---@field tool string

---@class SirnaDesign
---@field gate? any
---@field minReynolds? number
---@field ok any
---@field provenance table
---@field result table
---@field shRnaLoop? string
---@field target string
---@field tool string

---@class SirnaDesignCreateData
---@field gate? any
---@field minReynolds? number
---@field ok any
---@field provenance table
---@field result table
---@field shRnaLoop? string
---@field target string
---@field tool string

---@class SiteDirectedMutagenesi
---@field armTmTarget? number
---@field dntpMM? number
---@field editKind? string
---@field frameStart? number
---@field gate? any
---@field mgMM? number
---@field naMM? number
---@field newBase? string
---@field ok any
---@field oligoNM? number
---@field organism? string
---@field position? number
---@field provenance table
---@field residue? number
---@field result table
---@field style? string
---@field targetAa? string
---@field template string
---@field tool string

---@class SiteDirectedMutagenesiCreateData
---@field armTmTarget? number
---@field dntpMM? number
---@field editKind? string
---@field frameStart? number
---@field gate? any
---@field mgMM? number
---@field naMM? number
---@field newBase? string
---@field ok any
---@field oligoNM? number
---@field organism? string
---@field position? number
---@field provenance table
---@field residue? number
---@field result table
---@field style? string
---@field targetAa? string
---@field template string
---@field tool string

---@class Translate
---@field frame? number
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field toStop? boolean
---@field tool string

---@class TranslateCreateData
---@field frame? number
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field toStop? boolean
---@field tool string

---@class VariantAnnotate
---@field assembly? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string
---@field variant string

---@class VariantAnnotateCreateData
---@field assembly? string
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field tool string
---@field variant string

---@class VariantComparator
---@field coding? boolean
---@field frameStart? number
---@field gate? any
---@field ok any
---@field provenance table
---@field query string
---@field reference string
---@field result table
---@field tool string

---@class VariantComparatorCreateData
---@field coding? boolean
---@field frameStart? number
---@field gate? any
---@field ok any
---@field provenance table
---@field query string
---@field reference string
---@field result table
---@field tool string

---@class VerifyAssembly
---@field armTmTarget? number
---@field circular? boolean
---@field claimedConstruct string
---@field coding? boolean
---@field enzyme? string
---@field enzyme3? string
---@field enzyme5? string
---@field fragmentPcrs? table
---@field fragments? table
---@field frameStart? number
---@field gate? any
---@field insert? string
---@field insertPcr? table
---@field method string
---@field names? table
---@field ok any
---@field overlapLen? number
---@field provenance table
---@field result table
---@field tool string
---@field vector? string
---@field vectorPcr? table

---@class VerifyAssemblyCreateData
---@field armTmTarget? number
---@field circular? boolean
---@field claimedConstruct string
---@field coding? boolean
---@field enzyme? string
---@field enzyme3? string
---@field enzyme5? string
---@field fragmentPcrs? table
---@field fragments? table
---@field frameStart? number
---@field gate? any
---@field insert? string
---@field insertPcr? table
---@field method string
---@field names? table
---@field ok any
---@field overlapLen? number
---@field provenance table
---@field result table
---@field tool string
---@field vector? string
---@field vectorPcr? table

---@class VerifyConstruct
---@field claimedConstruct string
---@field expectedFrameStart? number
---@field gate? any
---@field insertForwardPrimer string
---@field insertReversePrimer string
---@field insertTemplate string
---@field maxPrimerMismatches? number
---@field ok any
---@field provenance table
---@field result table
---@field templateCircular? boolean
---@field tool string

---@class VerifyConstructCreateData
---@field claimedConstruct string
---@field expectedFrameStart? number
---@field gate? any
---@field insertForwardPrimer string
---@field insertReversePrimer string
---@field insertTemplate string
---@field maxPrimerMismatches? number
---@field ok any
---@field provenance table
---@field result table
---@field templateCircular? boolean
---@field tool string

---@class VirtualGel
---@field circular? boolean
---@field enzymes? table
---@field gate? any
---@field ladder? string
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class VirtualGelCreateData
---@field circular? boolean
---@field enzymes? table
---@field gate? any
---@field ladder? string
---@field ok any
---@field provenance table
---@field result table
---@field sequence string
---@field tool string

---@class VolcanoPlotData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field rows table
---@field tool string

---@class VolcanoPlotDataCreateData
---@field gate? any
---@field ok any
---@field provenance table
---@field result table
---@field rows table
---@field tool string

---@class WebSearch
---@field gate? any
---@field max_results? number
---@field ok any
---@field provenance table
---@field query string
---@field result table
---@field tool string

---@class WebSearchCreateData
---@field gate? any
---@field max_results? number
---@field ok any
---@field provenance table
---@field query string
---@field result table
---@field tool string

local M = {}

return M
