<?php
declare(strict_types=1);

// SeqbenchMcp SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

SeqbenchMcpUtility::setRegistrar(function (SeqbenchMcpUtility $u): void {
    $u->clean = [SeqbenchMcpClean::class, 'call'];
    $u->done = [SeqbenchMcpDone::class, 'call'];
    $u->make_error = [SeqbenchMcpMakeError::class, 'call'];
    $u->feature_add = [SeqbenchMcpFeatureAdd::class, 'call'];
    $u->feature_hook = [SeqbenchMcpFeatureHook::class, 'call'];
    $u->feature_init = [SeqbenchMcpFeatureInit::class, 'call'];
    $u->fetcher = [SeqbenchMcpFetcher::class, 'call'];
    $u->make_fetch_def = [SeqbenchMcpMakeFetchDef::class, 'call'];
    $u->make_context = [SeqbenchMcpMakeContext::class, 'call'];
    $u->make_options = [SeqbenchMcpMakeOptions::class, 'call'];
    $u->make_request = [SeqbenchMcpMakeRequest::class, 'call'];
    $u->make_response = [SeqbenchMcpMakeResponse::class, 'call'];
    $u->make_result = [SeqbenchMcpMakeResult::class, 'call'];
    $u->make_point = [SeqbenchMcpMakePoint::class, 'call'];
    $u->make_spec = [SeqbenchMcpMakeSpec::class, 'call'];
    $u->make_url = [SeqbenchMcpMakeUrl::class, 'call'];
    $u->param = [SeqbenchMcpParam::class, 'call'];
    $u->prepare_auth = [SeqbenchMcpPrepareAuth::class, 'call'];
    $u->prepare_body = [SeqbenchMcpPrepareBody::class, 'call'];
    $u->prepare_headers = [SeqbenchMcpPrepareHeaders::class, 'call'];
    $u->prepare_method = [SeqbenchMcpPrepareMethod::class, 'call'];
    $u->prepare_params = [SeqbenchMcpPrepareParams::class, 'call'];
    $u->prepare_path = [SeqbenchMcpPreparePath::class, 'call'];
    $u->prepare_query = [SeqbenchMcpPrepareQuery::class, 'call'];
    $u->graphql_body = [SeqbenchMcpGraphql::class, 'body'];
    $u->graphql_errors = [SeqbenchMcpGraphql::class, 'errors'];
    $u->result_basic = [SeqbenchMcpResultBasic::class, 'call'];
    $u->result_body = [SeqbenchMcpResultBody::class, 'call'];
    $u->result_headers = [SeqbenchMcpResultHeaders::class, 'call'];
    $u->transform_request = [SeqbenchMcpTransformRequest::class, 'call'];
    $u->transform_response = [SeqbenchMcpTransformResponse::class, 'call'];
});
